spring:
  application:
  name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: MySQL@123

    jpa:
      hibernate:
        ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect


